"use strict";
const express = require('express');
const router = express.Router();
const customerController = require('../controller/customer');
router.post('/customer',customerController.create);
router.get('/customer',customerController.getCustomer);
router.get('/customer/:id',customerController.getCustomerById);
router.put('/customer/:id',customerController.updateCustomer);
router.delete('/customer/:id',customerController.deleteCustomer);
//router.post('/send-mail',customerController.sendMail);
module.exports = router;